#!/bin/bash -e
#
#   busybox-kconfigdump - generates models in busybox source trees
#
# Copyright (C) 2012 Manuel Zerpies <manuel.f.zerpies@ww.stud.uni-erlangen.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script is used for precalculating the configuration models of a
# busybox tree. Therefore the config is first dumped with dumpconf to an
# rsf file. This rsf file is piped to rsf2model which calculates the
# model which is used by the undertaker afterwards.
#
# dumpconf and rsf2model can be placed in $PREFIX/lib/undertaker or
# /usr/lib/undertaker or /usr/local/lib/undertaker, because they won't
# be needed anywhere else than here.
#
# Enviroment variables:
# - MODELS: the directory where the models are placed (default:
#           models)
# - DEBUG: give some debug informations
#
# Arguments:
# - Architecture models to build


MODELS=${MODELS:-models}

function debug () {
    if [ -n "$DEBUG" ]; then
        echo -e "$@"
    fi
}

function find_undertaker_basepath () {
    # ensure to follow symbolic links
    local undertaker_path=$(readlink -f `which undertaker`)
    local b=$(dirname $undertaker_path)
    echo "${b}/.."
}

PATH="`find_undertaker_basepath`/lib/undertaker:$PATH"
debug "PATH=$PATH\n"

if ! which dumpconf > /dev/null; then
    echo "No dumpconf binary found."
    exit 1
fi

if ! which  rsf2model > /dev/null; then
    echo "No rsf2model binary found."
    exit 1
fi

if [ ! -f Config.in ]; then
    echo "Not run in a busybox tree. Please run inside a busybox tree without arguments"
    exit 1
fi

debug "rsf2model: $(which rsf2model)"
debug "dumpconf: $(which dumpconf)"

mkdir -p "$MODELS"
echo "Calculating model for busybox"

# generate config files, execute dumpconf
# remove all the comments because they will confuse rsf2model
make gen_build_files
dumpconf Config.in | sort -u | grep -v '^#' > "$MODELS/busybox.rsf"

# make models for busybox
rsf2model "$MODELS/busybox.rsf" > "$MODELS/busybox.model"
