#!/usr/bin/env python
#
#   rsf2model - extracts presence implications from kconfig dumps
#
# Copyright (C) 2011 Christian Dietrich <christian.dietrich@informatik.uni-erlangen.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os
import os.path
sys.path = [os.path.join(os.path.dirname(sys.path[0]), 'lib', 'python%d.%d' % \
                             (sys.version_info[0], sys.version_info[1]), 'site-packages')] \
                             + sys.path
from vamos.rsf2model import RsfReader
from vamos.rsf2model import TranslatedModel

if __name__ == '__main__':
    fd = sys.stdin
    if len(sys.argv) > 1:
        fd = open(sys.argv[1])
    rsf = RsfReader.RsfReader(fd)
    sys.stdout.write(str(TranslatedModel.TranslatedModel(rsf)))
