#!/bin/bash -e

PATH=/usr/bin:/bin:/proj/i4vamos/tools/$(whoami)/bin:/bin:/proj/i4vamos/tools/bin
export PATH

basedir="/srv/scratch/$(whoami)"
resultdir="/proj/i4vamos/users/$(whoami)/results"
giturl="git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6.git"

mkdir -p $resultdir
mkdir -p "$basedir"; cd "$basedir"
mkdir -p results

if [ ! -d linux-head ]; then
    git clone $giturl linux-head
fi

cd linux-head
git clean -fdxq
git reset --hard
git pull
version=$(git describe)
report="${resultdir}/${version}-report.txt"
deadlist="${resultdir}/${version}-deads.txt"
echo "Scanning version ${version}, logging to ${report}"
dump-rsf.sh     2&>1 >  "$report"
go.sh           2&>1 >> "$report"
find . -name '*dead' -ls > $deadlist
tail -2 "$report"
