#!/usr/bin/python

import sys
import os
from undertaker import RsfReader
from undertaker import TranslatedModel

if __name__ == '__main__':
    fd = sys.stdin
    if len(sys.argv) > 1:
        fd = open(sys.argv[1])
    rsf = RsfReader.RsfReader(fd)
    sys.stdout.write(str(TranslatedModel.TranslatedModel(rsf)))

