#!/usr/bin/env python

import sys
import os
import os.path
sys.path = [os.path.join(os.path.dirname(sys.path[0]), 'lib', 'python%d.%d' % \
                             (sys.version_info[0], sys.version_info[1]), 'site-packages')] \
                             + sys.path
from vamos.rsf2model import RsfReader
from vamos.rsf2model import TranslatedModel

if __name__ == '__main__':
    fd = sys.stdin
    if len(sys.argv) > 1:
        fd = open(sys.argv[1])
    rsf = RsfReader.RsfReader(fd)
    sys.stdout.write(str(TranslatedModel.TranslatedModel(rsf)))

